# HL: Horizontally Left-Aligned (Default) 水平居左 (默认)
# HC: Horizontally Centered 水平居中
# HR: Horizontally Right-Aligned  水平居右
# VT: Vertically Top-Aligned (Default) 垂直居上
# VC: Vertically Centered 垂直居中
# VB: Vertically Bottom-Aligned 垂直居下

[MenuText]
FileNum=数字键锁
FileCaps=大写键锁
FileScroll=滚动键锁
FileModify=修改配置
FileStart=开机启动
FileExit=安全退出
NumTips=数字开|数字关
CapsTips=大写开|大写关
ScrollTips=滚动开|滚动关

# 数字锁定
[NumLock]
# 窗口坐标偏移
HudOffset=0,50
# 屏幕对齐方式
HudAlignment=HC|VT
# 桌面图像
HudImageOn=NumLock_On.png
HudImageOff=NumLock_Off.png
# 托盘图标
TrayIconOn=NumLock_On.png
TrayIconOff=NumLock_Off.png
# 音效配置
SoundMuted=true
KeySoundOn=KeyLock_On.wav
KeySoundOff=KeyLock_Off.wav
# HUD 显示时长 (<=0 Ignore)
HudDisplayDuration=1
# 自动恢复锁定状态 (LOCK|UNLOCK|NONE)
AutoRestoreState=LOCK
# 恢复数字锁定延时 (<=0 Ignore)
AutoRestoreDelay=5

# 大写锁定
[CapsLock]
# 窗口坐标偏移
HudOffset=0,50
# 屏幕对齐方式
HudAlignment=HC|VT
# 桌面图像
HudImageOn=CapsLock_On.png
HudImageOff=CapsLock_Off.png
# 托盘图标
TrayIconOn=CapsLock_On.png
TrayIconOff=CapsLock_Off.png
# 音效配置
SoundMuted=true
KeySoundOn=KeyLock_On.wav
KeySoundOff=KeyLock_Off.wav
# HUD 显示时长 (<=0 Ignore)
HudDisplayDuration=1
# 自动恢复锁定状态 (LOCK|UNLOCK|NONE)
AutoRestoreState=UNLOCK
# 解除大写锁定延时 (<=0 Ignore)
AutoRestoreDelay=5

# 滚动锁定
[ScrollLock]
# 窗口坐标偏移
HudOffset=0,50
# 屏幕对齐方式
HudAlignment=HC|VT
# 桌面图像
HudImageOn=ScrollLock_On.png
HudImageOff=ScrollLock_Off.png
# 托盘图标
TrayIconOn=ScrollLock_On.png
TrayIconOff=ScrollLock_Off.png
# 音效配置
SoundMuted=true
KeySoundOn=KeyLock_On.wav
KeySoundOff=KeyLock_Off.wav
# HUD 显示时长 (<=0 Ignore)
HudDisplayDuration=1
# 自动恢复锁定状态 (LOCK|UNLOCK|NONE)
AutoRestoreState=UNLOCK
# 解除滚动锁定延时 (<=0 Ignore)
AutoRestoreDelay=5
